# 教材エンジン「あさひ」始動遷移ジェネレータ（集中定数系・Euler 50Hz）
# 出力: site/lab/mezame-data.js  仕様: notes/lab-mezame-plan.md
param([double]$kN = 500.0, [switch]$Emit)

function Clamp([double]$x,[double]$a,[double]$b){ [Math]::Min($b,[Math]::Max($a,$x)) }
function Ramp([double]$t,[double]$t0,[double]$t1){ Clamp (($t-$t0)/($t1-$t0)) 0 1 }

$dt = 0.02; $tStart = -0.5; $tEnd = 5.0
$kt = 76000.0; $Pp_rated = 7e6; $kpc = 0.181

# 状態
$N = 0.0; $Nox = 0.0; $Twall = 120.0; $pc = 0.0

$rows = New-Object System.Collections.Generic.List[object]
$t = $tStart
while($t -le $tEnd + 1e-9){
  $mfv = Ramp $t 0.0 0.3
  $mov = (Ramp $t 0.8 1.0)*0.2 + (Ramp $t 2.2 2.6)*0.8
  $tcv = 1.0 - 0.28*(Ramp $N 38000.0 45000.0)   # ガバナ: 回転で手綱を締める
  $ignited = ($t -ge 1.0)

  $mdot_f = $mfv * (0.6 + 5.4*$N/45000.0)
  $w = 0.85/(1.0 + $mdot_f/3.0)
  $Th = 50.0 + ($Twall-50.0)*$w
  $pr = 0.06 + 0.94*[Math]::Pow($N/45000.0, 1.5)   # タービン圧力比の効き
  $Pt = $tcv * $kt * (0.15*$mdot_f) * [Math]::Max($Th-45.0, 0) * $pr
  $Pp = $Pp_rated * [Math]::Pow($N/45000.0, 3)
  $mdot_o = $mov * (1.5 + 26.5*$Nox/16500.0)
  if($ignited){
    $eta = 0.6 + 0.4*(Ramp $t 1.0 1.8)
    $pcT = $kpc * (0.85*$mdot_f + $mdot_o) * $eta
  } else {
    $pcT = 0.05*$mdot_f
  }
  $MR = (Clamp ($mdot_o/([Math]::Max(0.85*$mdot_f, 0.05))) 0 8)
  $NPSHa = 50.0 + 25.0*(Ramp $t 3.0 4.6)
  $NPSHr = 45.0*[Math]::Pow($Nox/16500.0, 2)
  $marg = if($NPSHr -gt 1.0){ Clamp ($NPSHa/$NPSHr) 0 5 } else { 5.0 }
  $F = 50.0*$pc

  $rows.Add([pscustomobject]@{ t=$t; N=$N; Nox=$Nox; pc=$pc; F=$F; Th=$Th; Twall=$Twall; MR=$MR; npshm=$marg; mfv=$mfv; mov=$mov; tcv=$tcv })

  # 状態更新
  $N = [Math]::Max(0, $N + $kN*($Pt-$Pp)/($N+2000.0)*$dt)
  $Nox = $Nox + (16500.0*[Math]::Pow($N/45000.0,1.1) - $Nox)*$dt/0.25
  if($ignited){ $Twall = $Twall + 1.6*((150.0+450.0*$pc/($pc+0.8)) - $Twall)*$dt }
  else { $Twall = $Twall - ($Twall-90.0)*0.15*(0.5+$mdot_f)*$dt }
  $pc = $pc + ($pcT-$pc)*$dt/0.12
  $t = [Math]::Round($t + $dt, 4)
}

# チェックポイント表示（チューニング用）
foreach($ck in @(0,0.5,1.0,1.5,2.0,2.5,3.0,3.2,3.5,4.0,4.5,5.0)){
  $r = $rows | Where-Object { [Math]::Abs($_.t-$ck) -lt 0.011 } | Select-Object -First 1
  if($r){ "{0,5:f1}s  N={1,6:f0}rpm  Nox={2,6:f0}  pc={3,5:f2}MPa  F={4,6:f1}kN  Th={5,5:f0}K  Twall={6,5:f0}K  MR={7,4:f1}  marg={8,4:f2}" -f $r.t,$r.N,$r.Nox,$r.pc,$r.F,$r.Th,$r.Twall,$r.MR,$r.npshm }
}

if($Emit){
  $out = "C:\Users\kanedomi\Desktop\Claude\engine-zukan\site\lab\mezame-data.js"
  New-Item -ItemType Directory -Force (Split-Path $out) | Out-Null
  $inv = [Globalization.CultureInfo]::InvariantCulture
  function Ser($name, $digits){
    $vals = foreach($r in $rows){ ([Math]::Round($r.$name, $digits)).ToString($inv) }
    return "  $name`: [" + [string]::Join(",", $vals) + "],`n"
  }
  $js = "// generated by drafts/mezame/gen.ps1 - do not edit by hand`n"
  $js += "const MEZAME = { scenarios: { nominal: {`n  name: `"きほんの朝`", dt: 0.02, t0: -0.5,`n"
  $js += (Ser "t" 2) + (Ser "N" 0) + (Ser "Nox" 0) + (Ser "pc" 3) + (Ser "F" 1) + (Ser "Th" 1) + (Ser "Twall" 1) + (Ser "MR" 2) + (Ser "npshm" 2) + (Ser "mfv" 3) + (Ser "mov" 3) + (Ser "tcv" 3)
  $js += "}}};`n"
  [IO.File]::WriteAllText($out, $js)
  "emitted: $out (" + [int]((Get-Item $out).Length/1KB) + "KB)"
}
